name: Test V2Ray Servers
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      ACTIONS_RUNNER_DEBUG: true      
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd files
          pip install -r requirements.txt

      - name: Run server tests
        run: |
          python app.py

      - name: Check outbound connectivity
        
        run: |
          echo "Testing SOCKS5 proxy on port 20000..."
          curl -v --socks5-hostname 127.0.0.1:20000 https://www.google.com/generate_204 || echo "SOCKS5 test failed"

      - name: Upload server-test logs
        uses: actions/upload-artifact@v3
        with:
          name: v2ray-test-logs
          path: |
            logs/latest_log.txt
            "Tested Servers/dead_servers.txt"
