name: Proxy Server Tester
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  test-servers:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Create directories
      run: |
        New-Item -ItemType Directory -Force -Path Files,logs,"Tested Servers/Protocols",v2ray

    - name: Run Server Tester
      run: |
        python app.py --max-threads 6
      env:
        PYTHONUNBUFFERED: 1

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: windows-results
        path: |
          Tested\ Servers/
          logs/