name: Proxy Server Tester
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  test-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install -r requirements.txt

      - name: Create necessary directories
        run: |
          mkdir -p Files Tested\ Servers/Protocols logs

      - name: Run Proxy Tester
        run: python app.py --max-threads 15