name: Proxy Server Tester
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:


jobs:
  server-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl jq
        pip install -r requirements.txt
        
    - name: Run Server Tester
      run: |
        python app.py --max-threads 6
      env:
        PYTHONUNBUFFERED: 1
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          Tested\ Servers/
          logs/