name: Run V2Ray Server Tester

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '**.txt'
      - .github/workflows/run.yml

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app.py
        run: |
          python app.py --max-threads 5

      - name: Push Results Back to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Tested\ Servers/ logs/
          git commit -m "Add server test results from GitHub Actions" || echo "No changes to commit"
          git push
