name: Run V2Ray Server Tester
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r data/requirements.txt

    - name: Run V2Ray tester
      run: |
        echo "🧪 Running V2Ray server tester..."
        python app.py
      env:
        PYTHONUNBUFFERED: 1
     

    - name: Show recent logs
      run: |
        echo "📜 Showing latest logs:"
        tail -n 50 logs/channel_stats.log || echo "No log found."

    - name: Commit and push results
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: "📡 Updated tested V2Ray servers"
        add: "."
        push: true
